name: lint all
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
env:
  PRISMA_TELEMETRY_INFORMATION: "prisma-client-go lint.yml"

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-go@v1
        with:
          go-version: '1.15'

      - name: download
        run: go mod download

      - name: generate
        run: go generate ./...

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          version: v1.29
          args: --enable "gofmt,golint,scopelint,gocritic"
